### ISSUE TITLE
Experiencing White page after loading.

### ISSUE THREAD

**Issue by sparsh02** [sparsh02/Calorie_Journal_SAAS-based#1]
After node server loading, the site works fine for 10 seconds after which it reloads itself into a white blank screen.

**Comment by kishore881** [comment]
👋@sparsh02 I went through the code, and I see two issues responsible for this. Both originate from your [server's .env](https://github.com/sparsh02/Calorie_Journal_SAAS-based/blob/main/server/.env) file.
- PORT variable is set to 6000. However, everywhere in your client code, the port number used is 5000.
- DATABASE_URL still has `<` `>` around the password, and the DB rejects the connection request.

#### I fixed these two things, and the white page issue has stopped.

When using react, you can see all the warnings and errors are logged here. So take a look at them and work backward to figure out why. 

I noticed several other issues from the logs in the dev tools console. But I leave those to you to work out. 

Cheers!!!

**Comment by sparsh02** [comment]
Hi @kancherlakishorereddy , Thank you pointing out the issue, I have rectified the .env file, however the primary issue still pertains, the site loads fer a second or two, and then there comes the white screen. At first I thought it is due to .env too, but it doesn't seem the case, maybe something to do with the browser ?
